id: I848BFF45
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:16:00+00:00'
last_modified: '2022-06-08T18:02:21.876483+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3958
  title: མདོ་སྡེ་མེ་ཏོག་སིལ་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    611F:
      image_group_id: I1KG4016
      title: Volume 1 of mdo sde me tog sil ma
      total_pages: 414
      order: 1
      base_file: 611F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
