id: P008045
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3958
  title: མདོ་སྡེ་མེ་ཏོག་སིལ་མ།
  author: ''
  volumes:
    7207bda7d3ae4fbfb082faba1dfc1c4f:
      image_group_id: I1KG4016
      title: ''
      volume_number: 1
      total_pages: 414
ebook_metadata:
  title: མདོ་སྡེ་མེ་ཏོག་སིལ་མ།
  author: ''
  sku: P008045
  cover: cover.jpg
  layers:
  - pagination
